spring:
  data:
    mongodb:
      address: 39.106.133.40:27017
      authentication-database: ims
      username: klk_ims
      password: ims123456
      auth: true
      database: ims
      authenticationDatabase: ims
      min-connection-per-host: 10
      max-connection-per-host: 100
      max-wait-time: 10000

server:
  servlet:
    context-path: /ims
  port: 8080

activemq:
  username: amq_ims
  password: amq_ims_123456
  url: tcp://39.106.133.40:61616