host: 192.168.183.100
spring:
  data:
    mongodb:
      address: ${host}:27017
  datasource:
    url: jdbc:mysql://${host}/messager?zeroDateTimeBehavior=convertToNull&socketTimeout=60000&autoReconnect=true&useSSL=false
  redis:
    host: ${host}
activemq:
  url: tcp://${host}:61616