host: 192.168.1.100
spring:
  data:
    mongodb:
      address: ${host}:27017
  datasource:
    url: jdbc:mysql://${host}/messager?zeroDateTimeBehavior=convertToNull&socketTimeout=60000&autoReconnect=true
  redis:
    host: ${host}
activemq:
  url: failover:(tcp://${host}:61616)