spring:
  data:
    mongodb:
      authentication-database: admin
      username: klk_ims
      password: ims123456
      auth: true
      database: ims
      authenticationDatabase: ims
      min-connection-per-host: 2
      max-connection-per-host: 5
      max-wait-time: 10000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: konglk
    password: konglk
    hikari:
      maximum-pool-size: 8
      minimum-idle: 3
  activemq:
    user: amq_ims
    password: amq_ims_123456
    pool:
      enabled: false
      max-connections: 5
      idle-timeout: 120
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    port: 6379
    password: redis_ims
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 0
        max-wait: 10000
    so-timeout: 5000

server:
  servlet:
    context-path: /ims
  port: 8080

activemq:
  username: amq_ims
  password: amq_ims_123456
